apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: foos.crdcontroller.com
spec:
  group: crdcontroller.com

  versions:
    - name: v1alpha1
      served: true
      storage: true

  names:
    kind: Foo
    plural: foos
    singular: foo
    shortNames:
      - f
  scope: Namespaced
